# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90687ca83a9ff6c351c5ff09a5007317d392314e6b9978101ae6d4bd1bf208826d6e276d80101db07433433c30902413c92b7071503885ca16ff4a0d7c7ff486

test:
  secret_key_base: 2ba49bf45b2a29cc87237c2e86117122a2c18d0d16eb83d8acd89b84ab902b08637e491411fcaa9d346df967fa04dd6bd94d3204ea9d61b9e6a57512c8d86dbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
